In [ ]:
#4 TO - DO - Task

#Sol 1-
import numpy as np
empty_array=np.empty((2,2))
print(empty_array)


#Sol 2-
ones_array=np.ones((4,2))
print(ones_array)

#Sol 3-
shape=(3,3)
fill_value=7
filled_array=np.full(shape,fill_value)
print(filled_array)


#Sol 4-
reference_array=np.array([[1,2],[3,4]])
zeros_array=np.zeros_like(reference_array)
print(zeros_array)


#Sol 5-
ones_like_arrray=np.ones_like(reference_array)
print(ones_like_array)


#Sol 6-
new_list=[1,2,3,4]
np_array=np.array(new_list)
print(np_array)




In [ ]:
#4.1.1 Problem - 2: Array Manipulation: Numerical Ranges & Array indexing:

#Sol 1-
import numpy as np
arr_1=np.arange(10,50)
print(arr_1)


#Sol 2-
arr_2=np.arange(9).reshape(3,3)
print(arr_2)



#Sol 3-
arr_3=np.eye(3)
print(arr_3)



#Sol 4-
arr_4=np.random.random(30)
mean_value=arr_4.mean()
print("Random array:",arr_4)
print("Mean",mean_value)


#Sol 5-
arr_5=np.random.random((10,10))
min_value=arr_5.min()
max_value=arr_5.max()
print("random 10*10 array:\n",arr_5)
print("min value:",min_value)
print("max value:",max_value)


#Sol 6-
arr_6=np.zeros(10)
arr_6[4]=1
print(arr_6)


#Sol 7-
arr_7=np.array([1,2,0,0,4,0])
reversed_arr=arr_7[::-1]
print(reversed_arr)


#Sol 8-
arr_8=np.ones((5,5))
arr_8[1:-1,1:-1]=0
printz(arr_8)


#Sol 9-
arr_9=np.zeros((8,8),dtype=int)
arr_9[1:2,::2]=1
arr_9[::2,1::2]=1
print(arr_9)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array: [0.22550901 0.67186636 0.41326938 0.20936123 0.95275804 0.73703684
 0.13993916 0.348754   0.17871819 0.21838752 0.95109867 0.35026374
 0.25183169 0.7800549  0.54478127 0.14859829 0.52324349 0.11488265
 0.43661971 0.40710817 0.95657083 0.45693827 0.90936686 0.08335205
 0.13268219 0.03208642 0.50099645 0.50867273 0.04827506 0.97953124]
Mean 0.44041847969498515
random 10*10 array:
 [[0.34467276 0.90085061 0.33687491 0.10585125 0.0892351  0.00459552
  0.96657158 0.03395638 0.28477306 0.41960809]
 [0.6422588  0.22081105 0.31272357 0.93786612 0.22211583 0.57187452
  0.12809022 0.27842294 0.74104357 0.3934562 ]
 [0.27814508 0.6985434  0.10855196 0.36423063 0.39020859 0.38117992
  0.02643252 0.38761298 0.87868282 0.62098801]
 [0.34198289 0.82224865 0.81794641 0.76825981 0.58368054 0.65423625
  0

NameError: name 'printz' is not defined

In [ ]:
#Problem-3: Array operations:

#Sol 1-
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

add_result = x + y
print("Addition of x and y:\n", add_result)


#Sol 2-
subtract_result = x - y
print("Subtraction of x and y:\n", subtract_result)


#Sol 3-
multiply_x = x * 2
multiply_y = y * 3
print("x multiplied by 2:\n", multiply_x)
print("y multiplied by 3:\n", multiply_y)


#Sol 4-
square_x = np.square(x)
square_y = np.square(y)
print("Square of each element of x:\n", square_x)
print("Square of each element of y:\n", square_y)


#Sol 5-
v = np.array([9, 10])
w = np.array([11, 12])

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("Dot product between v and w:", dot_vw)
print("Dot product between x and v:\n", dot_xv)
print("Dot product between x and y:\n", dot_xy)
