In [ ]:
#4 TO - DO - Task

#Sol 1-
import numpy as np
empty_array=np.empty((2,2))
print(empty_array)


#Sol 2-
ones_array=np.ones((4,2))
print(ones_array)

#Sol 3-
shape=(3,3)
fill_value=7
filled_array=np.full(shape,fill_value)
print(filled_array)


#Sol 4-
reference_array=np.array([[1,2],[3,4]])
zeros_array=np.zeros_like(reference_array)
print(zeros_array)


#Sol 5-
ones_like_arrray=np.ones_like(reference_array)
print(ones_like_array)


#Sol 6-
new_list=[1,2,3,4]
np_array=np.array(new_list)
print(np_array)




In [1]:
#4.1.1 Problem - 2: Array Manipulation: Numerical Ranges & Array indexing:

#Sol 1-
import numpy as np
arr_1=np.arange(10,50)
print(arr_1)


#Sol 2-
arr_2=np.arange(9).reshape(3,3)
print(arr_2)



#Sol 3-
arr_3=np.eye(3)
print(arr_3)



#Sol 4-
arr_4=np.random.random(30)
mean_value=arr_4.mean()
print("Random array:",arr_4)
print("Mean",mean_value)


#Sol 5-
arr_5=np.random.random((10,10))
min_value=arr_5.min()
max_value=arr_5.max()
print("random 10*10 array:\n",arr_5)
print("min value:",min_value)
print("max value:",max_value)


#Sol 6-
arr_6=np.zeros(10)
arr_6[4]=1
print(arr_6)


#Sol 7-
arr_7=np.array([1,2,0,0,4,0])
reversed_arr=arr_7[::-1]
print(reversed_arr)


#Sol 8-
arr_8=np.ones((5,5))
arr_8[1:-1,1:-1]=0
printz(arr_8)


#Sol 9-
arr_9=np.zeros((8,8),dtype=int)
arr_9[1:2,::2]=1
arr_9[::2,1::2]=1
print(arr_9)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array: [0.42355796 0.98974909 0.90532102 0.32477061 0.11758671 0.11307372
 0.45768535 0.73333749 0.95348488 0.2743641  0.50770023 0.70048558
 0.78815516 0.66779899 0.36675514 0.87600054 0.2825757  0.33712658
 0.18656279 0.90826139 0.08582346 0.93014422 0.65121965 0.09464946
 0.4749698  0.44513523 0.59881436 0.55655799 0.91073796 0.94104556]
Mean 0.5534483566112144
random 10*10 array:
 [[0.07927383 0.85693406 0.29203682 0.70208568 0.44494059 0.10528319
  0.41366921 0.63319746 0.6748573  0.49748616]
 [0.02089783 0.45466948 0.09679432 0.99753378 0.62135303 0.49968436
  0.72418188 0.00138403 0.32430739 0.479804  ]
 [0.17754625 0.63623971 0.17574445 0.40031798 0.00979877 0.48263237
  0.9700309  0.94963886 0.18386164 0.2297421 ]
 [0.05009147 0.15298021 0.8013173  0.95567655 0.36831304 0.82739714
  0.

NameError: name 'printz' is not defined

In [ ]:
#Problem-3: Array operations:

#Sol 1-
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

add_result = x + y
print("Addition of x and y:\n", add_result)


#Sol 2-
subtract_result = x - y
print("Subtraction of x and y:\n", subtract_result)


#Sol 3-
multiply_x = x * 2
multiply_y = y * 3
print("x multiplied by 2:\n", multiply_x)
print("y multiplied by 3:\n", multiply_y)


#Sol 4-
square_x = np.square(x)
square_y = np.square(y)
print("Square of each element of x:\n", square_x)
print("Square of each element of y:\n", square_y)


#Sol 5-
v = np.array([9, 10])
w = np.array([11, 12])

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("Dot product between v and w:", dot_vw)
print("Dot product between x and v:\n", dot_xv)
print("Dot product between x and y:\n", dot_xy)
